--
-- ORACLE DWH ETL SNIPPETS
--

-- 1. DDL: DIMENSION TABLE (SCD2 TYPE 2)
CREATE TABLE DWH_STG.DIM_LOAN_ATTR (
    X_HUB_KEY             VARCHAR2(40) NOT NULL,
    X_SAT_KEY             VARCHAR2(40) NOT NULL,
    CONTRACT_ID           VARCHAR2(50) NOT NULL,
    BANK_ID               VARCHAR2(20) NOT NULL,
    LOAN_STATUS_CD        VARCHAR2(20),
    LOAN_STATUS_DESC      VARCHAR2(200),
    RATE_TYPE_CD          VARCHAR2(10),
    MATURITY_DT           DATE,
    X_EFFECTIVE_FROM_DT   DATE NOT NULL,
    X_EFFECTIVE_TO_DT     DATE DEFAULT TO_DATE('99991231','YYYYMMDD') NOT NULL,
    X_CURRENT_FL          CHAR(1) DEFAULT 'Y' NOT NULL,
    X_INSERT_TS           TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_DIM_LOAN_ATTR PRIMARY KEY (X_HUB_KEY, X_EFFECTIVE_FROM_DT)
)
PARTITION BY RANGE (X_EFFECTIVE_FROM_DT) INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) (
    PARTITION P_INIT VALUES LESS THAN (TO_DATE('20240101','YYYYMMDD'))
);

CREATE INDEX IDX_DIM_LOAN_NK ON DWH_STG.DIM_LOAN_ATTR (CONTRACT_ID, BANK_ID) LOCAL;
CREATE INDEX IDX_DIM_LOAN_CURR ON DWH_STG.DIM_LOAN_ATTR (X_HUB_KEY, X_CURRENT_FL) LOCAL;

-- 2. DDL: FACT TABLE (MONTHLY SNAPSHOT)
CREATE TABLE DWH_STG.FACT_LOAN_MONTHLY (
    REF_MONTH_ID          NUMBER(6) NOT NULL, -- YYYYMM
    X_HUB_KEY             VARCHAR2(40) NOT NULL,
    BANK_ID               VARCHAR2(20) NOT NULL,
    OUTSTANDING_AMT       NUMBER(18,2),
    INTEREST_AMT          NUMBER(18,2),
    SOURCE_SYSTEM_CD      VARCHAR2(20),
    X_INSERT_TS           TIMESTAMP(6) DEFAULT SYSTIMESTAMP
)
PARTITION BY LIST (REF_MONTH_ID) 
SUBPARTITION BY LIST (SOURCE_SYSTEM_CD) (
    PARTITION P_202401 VALUES (202401) (
        SUBPARTITION P_202401_SRC1 VALUES ('SYSTEM_A'),
        SUBPARTITION P_202401_SRC2 VALUES ('SYSTEM_B')
    )
);

-- 3. PL/SQL PACKAGE SPECIFICATION
CREATE OR REPLACE PACKAGE DWH_ETL.PKG_LOAN_LOAD AS
    PROCEDURE LOAD_SCD2_DIMENSION(p_proc_date IN DATE);
    PROCEDURE LOAD_FACT_MONTHLY(p_ref_month IN NUMBER);
    FUNCTION GENERATE_HASH(p_input IN VARCHAR2) RETURN VARCHAR2;
END PK_LOAN_LOAD;
/

-- 4. PL/SQL PACKAGE BODY
CREATE OR REPLACE PACKAGE BODY DWH_ETL.PKG_LOAN_LOAD AS

    FUNCTION GENERATE_HASH(p_input IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN LOWER(RAWTOHEX(STANDARD_HASH(p_input, 'SHA256')));
    END;

    PROCEDURE LOAD_SCD2_DIMENSION(p_proc_date IN DATE) IS
    BEGIN
        -- Close existing versions
        UPDATE DWH_STG.DIM_LOAN_ATTR
        SET X_EFFECTIVE_TO_DT = p_proc_date - INTERVAL '1' SECOND,
            X_CURRENT_FL = 'N'
        WHERE X_CURRENT_FL = 'Y'
          AND X_HUB_KEY IN (SELECT X_HUB_KEY FROM DWH_STG.STG_LOAN_DELTA);

        -- Insert new versions
        INSERT INTO DWH_STG.DIM_LOAN_ATTR (...)
        SELECT ... FROM DWH_STG.STG_LOAN_DELTA;
        
        COMMIT;
    END;

    PROCEDURE LOAD_FACT_MONTHLY(p_ref_month IN NUMBER) IS
    BEGIN
        MERGE /*+ APPEND PARALLEL(8) */ INTO DWH_STG.FACT_LOAN_MONTHLY t
        USING (...) s
        ON (t.REF_MONTH_ID = s.REF_MONTH_ID AND t.X_HUB_KEY = s.X_HUB_KEY)
        WHEN MATCHED THEN UPDATE SET t.OUTSTANDING_AMT = s.OUTSTANDING_AMT
        WHEN NOT MATCHED THEN INSERT (...) VALUES (...);
        
        COMMIT;
    END;
END PK_LOAN_LOAD;
/
