-- =============================================================================
-- ORACLE DWH ETL SNIPPETS (ANONYMIZED FOR INTERVIEW)
-- SCD Type 7 Implementation: History Table + Current Table
-- Includes: Partitioning, Indexing, SCD7 Pattern, PL/SQL Package, Performance Hints
-- =============================================================================

-- 1. HISTORY TABLE (SCD Type 2 - stores all versions with effective dating)
CREATE TABLE DWH_STG.DIM_LOAN_ATTR_HIST (
    X_HUB_KEY             VARCHAR2(40) NOT NULL,
    X_SAT_KEY             VARCHAR2(40) NOT NULL,
    CONTRACT_ID           VARCHAR2(50) NOT NULL,
    BANK_ID               VARCHAR2(20) NOT NULL,
    LOAN_STATUS_CD        VARCHAR2(20),
    LOAN_STATUS_DESC      VARCHAR2(200),
    RATE_TYPE_CD          VARCHAR2(10),
    MATURITY_DT           DATE,
    X_EFFECTIVE_FROM_DT   DATE NOT NULL,
    X_EFFECTIVE_TO_DT     DATE DEFAULT TO_DATE('99991231','YYYYMMDD') NOT NULL,
    X_INSERT_TS           TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_DIM_LOAN_HIST PRIMARY KEY (X_HUB_KEY, X_EFFECTIVE_FROM_DT)
)
PARTITION BY RANGE (X_EFFECTIVE_FROM_DT) INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) (
    PARTITION P_INIT VALUES LESS THAN (TO_DATE('20240101','YYYYMMDD'))
);

CREATE INDEX IDX_DIM_LOAN_HIST_NK ON DWH_STG.DIM_LOAN_ATTR_HIST (CONTRACT_ID, BANK_ID) LOCAL;
CREATE INDEX IDX_DIM_LOAN_HIST_RANGE ON DWH_STG.DIM_LOAN_ATTR_HIST (X_EFFECTIVE_FROM_DT, X_EFFECTIVE_TO_DT) LOCAL;

-- 2. CURRENT TABLE (SCD Type 1 - always reflects latest state, no partitioning)
CREATE TABLE DWH_STG.DIM_LOAN_ATTR_CURR (
    X_HUB_KEY             VARCHAR2(40) NOT NULL,
    X_SAT_KEY             VARCHAR2(40) NOT NULL,
    CONTRACT_ID           VARCHAR2(50) NOT NULL,
    BANK_ID               VARCHAR2(20) NOT NULL,
    LOAN_STATUS_CD        VARCHAR2(20),
    LOAN_STATUS_DESC      VARCHAR2(200),
    RATE_TYPE_CD          VARCHAR2(10),
    MATURITY_DT           DATE,
    X_EFFECTIVE_FROM_DT   DATE NOT NULL,
    X_INSERT_TS           TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_DIM_LOAN_CURR PRIMARY KEY (X_HUB_KEY)
);

CREATE INDEX IDX_DIM_LOAN_CURR_NK ON DWH_STG.DIM_LOAN_ATTR_CURR (CONTRACT_ID, BANK_ID);

-- 3. MATERIALIZED VIEW (optional SCD7 bridge: current view of history)
CREATE MATERIALIZED VIEW DWH_STG.DIM_LOAN_ATTR_MV AS
  SELECT 
    X_HUB_KEY,
    X_SAT_KEY,
    CONTRACT_ID,
    BANK_ID,
    LOAN_STATUS_CD,
    LOAN_STATUS_DESC,
    RATE_TYPE_CD,
    MATURITY_DT,
    X_EFFECTIVE_FROM_DT,
    X_EFFECTIVE_TO_DT,
    X_INSERT_TS
  FROM DWH_STG.DIM_LOAN_ATTR_HIST
  WHERE X_EFFECTIVE_TO_DT = TO_DATE('99991231','YYYYMMDD')
  AND X_HUB_KEY IN (SELECT X_HUB_KEY FROM DWH_STG.DIM_LOAN_ATTR_CURR);

-- 4. FACT TABLE (MONTHLY SNAPSHOT)
CREATE TABLE DWH_STG.FACT_LOAN_MONTHLY (
    REF_MONTH_ID          NUMBER(6) NOT NULL, -- YYYYMM
    X_HUB_KEY             VARCHAR2(40) NOT NULL,
    BANK_ID               VARCHAR2(20) NOT NULL,
    OUTSTANDING_AMT       NUMBER(18,2),
    INTEREST_AMT          NUMBER(18,2),
    SOURCE_SYSTEM_CD      VARCHAR2(20),
    X_INSERT_TS           TIMESTAMP(6) DEFAULT SYSTIMESTAMP
)
PARTITION BY LIST (REF_MONTH_ID) 
SUBPARTITION BY LIST (SOURCE_SYSTEM_CD) (
    PARTITION P_202401 VALUES (202401) (
        SUBPARTITION P_202401_SRC1 VALUES ('SYSTEM_A'),
        SUBPARTITION P_202401_SRC2 VALUES ('SYSTEM_B')
    )
);

-- 5. PL/SQL PACKAGE SPECIFICATION
CREATE OR REPLACE PACKAGE DWH_ETL.PKG_LOAN_LOAD AS
    PROCEDURE LOAD_SCD7_DIMENSION(p_proc_date IN DATE);
    PROCEDURE LOAD_FACT_MONTHLY(p_ref_month IN NUMBER);
    FUNCTION GENERATE_HASH(p_input IN VARCHAR2) RETURN VARCHAR2;
END PKG_LOAN_LOAD;
/

-- 6. PL/SQL PACKAGE BODY
CREATE OR REPLACE PACKAGE BODY DWH_ETL.PKG_LOAN_LOAD AS

    FUNCTION GENERATE_HASH(p_input IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN LOWER(RAWTOHEX(STANDARD_HASH(p_input, 'SHA256')));
    END GENERATE_HASH;

    PROCEDURE LOAD_SCD7_DIMENSION(p_proc_date IN DATE) IS
    BEGIN
        -- Step 1: Close existing versions in HISTORY table (mark as expired)
        UPDATE DWH_STG.DIM_LOAN_ATTR_HIST h
        SET X_EFFECTIVE_TO_DT = p_proc_date - INTERVAL '1' SECOND
        WHERE X_EFFECTIVE_TO_DT = TO_DATE('99991231','YYYYMMDD')
          AND X_HUB_KEY IN (SELECT X_HUB_KEY FROM DWH_STG.STG_LOAN_DELTA);

        -- Step 2: Insert new versions into HISTORY table
        INSERT INTO DWH_STG.DIM_LOAN_ATTR_HIST 
        (
            X_HUB_KEY, X_SAT_KEY, CONTRACT_ID, BANK_ID, LOAN_STATUS_CD, 
            LOAN_STATUS_DESC, RATE_TYPE_CD, MATURITY_DT, X_EFFECTIVE_FROM_DT
        )
        SELECT 
            GENERATE_HASH(CONTRACT_ID || '#' || BANK_ID),
            GENERATE_HASH(LOAN_STATUS_CD || '#' || OUTSTANDING_AMT),
            CONTRACT_ID,
            BANK_ID,
            LOAN_STATUS_CD,
            LOAN_STATUS_DESC,
            RATE_TYPE_CD,
            MATURITY_DT,
            p_proc_date
        FROM DWH_STG.STG_LOAN_DELTA;

        -- Step 3: Merge into CURRENT table (SCD1 - replace entire row)
        MERGE INTO DWH_STG.DIM_LOAN_ATTR_CURR c
        USING (
            SELECT 
                GENERATE_HASH(CONTRACT_ID || '#' || BANK_ID) AS X_HUB_KEY,
                GENERATE_HASH(LOAN_STATUS_CD || '#' || OUTSTANDING_AMT) AS X_SAT_KEY,
                CONTRACT_ID,
                BANK_ID,
                LOAN_STATUS_CD,
                LOAN_STATUS_DESC,
                RATE_TYPE_CD,
                MATURITY_DT,
                p_proc_date AS X_EFFECTIVE_FROM_DT
            FROM DWH_STG.STG_LOAN_DELTA
        ) s
        ON (c.X_HUB_KEY = s.X_HUB_KEY)
        WHEN MATCHED THEN 
            UPDATE SET 
                c.X_SAT_KEY = s.X_SAT_KEY,
                c.LOAN_STATUS_CD = s.LOAN_STATUS_CD,
                c.LOAN_STATUS_DESC = s.LOAN_STATUS_DESC,
                c.RATE_TYPE_CD = s.RATE_TYPE_CD,
                c.MATURITY_DT = s.MATURITY_DT,
                c.X_EFFECTIVE_FROM_DT = s.X_EFFECTIVE_FROM_DT
        WHEN NOT MATCHED THEN 
            INSERT (
                X_HUB_KEY, X_SAT_KEY, CONTRACT_ID, BANK_ID, LOAN_STATUS_CD,
                LOAN_STATUS_DESC, RATE_TYPE_CD, MATURITY_DT, X_EFFECTIVE_FROM_DT
            )
            VALUES (
                s.X_HUB_KEY, s.X_SAT_KEY, s.CONTRACT_ID, s.BANK_ID, s.LOAN_STATUS_CD,
                s.LOAN_STATUS_DESC, s.RATE_TYPE_CD, s.MATURITY_DT, s.X_EFFECTIVE_FROM_DT
            );

        COMMIT;
    END LOAD_SCD7_DIMENSION;

    PROCEDURE LOAD_FACT_MONTHLY(p_ref_month IN NUMBER) IS
    BEGIN
        MERGE /*+ APPEND PARALLEL(8) */ INTO DWH_STG.FACT_LOAN_MONTHLY t
        USING (
            SELECT 
                p_ref_month AS REF_MONTH_ID,
                X_HUB_KEY,
                BANK_ID,
                OUTSTANDING_AMT,
                INTEREST_AMT,
                SOURCE_SYSTEM_CD
            FROM DWH_STG.STG_LOAN_MONTHLY
        ) s
        ON (t.REF_MONTH_ID = s.REF_MONTH_ID AND t.X_HUB_KEY = s.X_HUB_KEY)
        WHEN MATCHED THEN 
            UPDATE SET 
                t.OUTSTANDING_AMT = s.OUTSTANDING_AMT,
                t.INTEREST_AMT = s.INTEREST_AMT
        WHEN NOT MATCHED THEN 
            INSERT (
                REF_MONTH_ID, X_HUB_KEY, BANK_ID, OUTSTANDING_AMT, INTEREST_AMT, SOURCE_SYSTEM_CD
            )
            VALUES (
                s.REF_MONTH_ID, s.X_HUB_KEY, s.BANK_ID, s.OUTSTANDING_AMT, s.INTEREST_AMT, s.SOURCE_SYSTEM_CD
            );
        
        COMMIT;
    END LOAD_FACT_MONTHLY;

END PKG_LOAN_LOAD;
/